// Mocks generated by Mockito 5.3.2 from annotations
// in test_app/test/widget_tests.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_app/src/utils/color_generator.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeColor_0 extends _i1.SmartFake implements _i2.Color {
  _FakeColor_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ColorGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockColorGenerator extends _i1.Mock implements _i3.ColorGenerator {
  MockColorGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Color generate() => (super.noSuchMethod(
        Invocation.method(
          #generate,
          [],
        ),
        returnValue: _FakeColor_0(
          this,
          Invocation.method(
            #generate,
            [],
          ),
        ),
      ) as _i2.Color);
}
